FROM rust:1.72-slim-bookworm AS builder

WORKDIR /app

COPY Cargo.toml .
COPY Cargo.lock .

RUN cargo build --release

COPY src ./src

RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/target/release/encrypted_chat_program /app/encrypted_chat_program

EXPOSE 8001

CMD ["./encrypted_chat_program"]